SELECT
         TRY_CAST(DDATE AS DATE) AS DATE
         ,SALESPERSON
         ,CUSTOMERNAME
         ,CARMODEL
         ,CARMAKE
         ,TRY_CAST(CARYEAR AS NUMBER) AS CARYEAR
         ,SALEPRICE
         ,COMMISSIONRATE AS RATE
         ,COMMISSIONEARNED AS COMNE
FROM {{ source("raw_bi_car","CAR_SALES")}}
WHERE TRY_CAST(DDATE AS DATE)> '2020-01-01'