SELECT
         TRY_CAST(DDATE AS DATE) AS DDATE
         ,SALESPERSON
         ,CUSTOMERNAME
         ,CARMODEL
         ,CARMAKE
         ,TRY_CAST(CARYEAR AS NUMBER) AS CARYEAR
         ,SALEPRICE
         ,COMMISSIONRATE AS RATE
         ,COMMISSIONEARNED AS COMNEA
FROM {{source("raw_bi_car","CAR_SALES")}}
WHERE TRY_CAST(DDATE AS DATE)> '2020-01-01'